### ISSUE TITLE
(Too) Short timers confuse adapter datapoints

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#1020]
Might be a problem from amazon's side and the adapter cannot do anything about it, but as I don't know, I'd like to mention it here.  O:)

Timers of
- 5 seconds and less (with "keep listening" off)
- 9 seconds and less ("keep listening" on)
Set
alexa2.0.Echo-Devices.XXX.Timer.triggered
instantly to "false", after setting it to "true" (and sometimes all in
alexa2.0.Echo-Devices.XXX.Timer
is cleared at that point, too).

**Comment by Apollon77** [comment]
Yes this is very good the case. We would need debug logs of such cases to trace the root causes ... but in fact for you how it works:

* There comes a timer notification in (some 100 ms till second(s) later then you did it per voice)
* Then we update all timers from the API and recreate all relevat states for the added/changed/all ones, then timer get calculated for trigger states
All this can easiely take some seconds ...

So I would right now not like to spend too much effort into it because most likely it is simply "timing" and the whole usage is not suied for that short stuff (because not really likely in a normal case with humans).

So if you like grab debug logs with infos for such cases
