### ISSUE TITLE
Connect to Amazon not possible

### ISSUE THREAD

**Issue by planetofrock** [Apollon77/ioBroker.alexa2#1119]
Hello.

Unable to log in to Amazon Alexa.
Logfile: Error: Please open http://172.22.0.3:39439/ with your browser and login to Amazon. The cookie will be output here after successfull login.

However, it is not possible to access the website.

Version: 3.26.3

Greetz
Pawel

**Comment by Draygv2** [comment]
Same here

**Comment by pixelpuxel** [comment]
Similar here: I can connect, however after the login process I get a 404 error from amazon and no coockie is saved.

**Comment by Apollon77** [comment]
First of all (because first log looks like docker usage??) You need to configure the UP which can be used to call this in your browser, For docker this also might mean you need to define a port and forward this and such!

@pixelpuxel Your issue seems the usual "old OTP/2FA method configured" issue which is mentioned in readme troubleshooting. Please update the 2FA method.

**Comment by Draygv2** [comment]
Hi Apollon
I use the actual 2FA but it  still doesn't work. 

`<html>
<body>

alexa2.0 | Zeit | debug | Nachricht
-- | -- | -- | --
alexa2.0 | 2023-12-27 07:47:00.066 | debug | [HPM] Error occurred while proxying request 10.2.2.30:37781/favicon.ico to https://www.amazon.com/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
alexa2.0 | 2023-12-27 07:47:00.065 | debug | ERROR: Error: connect ETIMEDOUT 31.169.123.30:443
alexa2.0 | 2023-12-27 07:44:49.045 | debug | Router: /favicon.ico / GET / {"host":"10.2.2.30:37781","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0","accept":"image/avif,image/webp,*/*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate","connection":"keep-alive","referer":"http://10.2.2.30:37781/"}
alexa2.0 | 2023-12-27 07:44:48.994 | debug | [HPM] Error occurred while proxying request 10.2.2.30:37781/ to https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A454543303041343035443443313331423038303630384146434136423535383023413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=duQcrAQcc8mQv_rSJQhWzY97Zd2QlbC9HYQV04b9-rg&language=de_DE [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
alexa2.0 | 2023-12-27 07:44:48.993 | debug | ERROR: Error: connect ETIMEDOUT 31.169.123.30:443
alexa2.0 | 2023-12-27 07:43:08.642 | debug | [HPM] Error occurred while proxying request 10.2.2.30:37781/favicon.ico to https://www.amazon.com/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
alexa2.0 | 2023-12-27 07:43:08.642 | debug | ERROR: Error: connect ETIMEDOUT 31.169.123.30:443
alexa2.0 | 2023-12-27 07:42:39.594 | debug | Alexa-Cookie: Headers: {"upgrade-insecure-requests":"1","connection":"close","accept-encoding":"gzip, deflate","accept-language":"de-DE","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","user-agent":"AppleWebKit PitanguiBridge/2.2.485407.0-[HARDWARE=iPhone10_4][SOFTWARE=15.5][DEVICE=iPhone]","host":"www.amazon.com","authority":"www.amazon.com","sentry-trace":"e88d9e5fdd554eafb46e6b44ea37fca3-a965dbc43b5a8520","baggage":"sentry-environment=production,sentry-release=iobroker.alexa2%403.26.3,sentry-public_key=e9ac55f23fe149e78b1eab9ed4bf26ad,sentry-trace_id=e88d9e5fdd554eafb46e6b44ea37fca3","cookie":"frc=tDx9sYlY3fI+FS50sJmCOeTzENf+ckfjJ6ChZevVXgTMG2uVGOdQNHYQ3EJ+PkokBYkhQkBQUZQhIhitwNCHhsGxxH8KdbE5O/3ew8+OgGHCASVTjdu4QzfECv4ShWfklpRbu9LFK8z8F96jc9b1DyAEEo5ISSFWY4eg5+IORy0C6B+CCWxCF4kFwbt5J9czgeWsBjPQQuxEgKZrOOqaEsHjLfiGuJXgNuiK9oYpiD/OKQ79JtkR3J3w2w9HCbry0FfYhiphScy2X+R3XObtLddg12BMs+0g8IO2NCUyA72tWHceVDwoMLR2arC7DXYAxzzPsY4hdWN6NCqx8K75cOO7ksV6Sx4CdVP0R13Cb0JOrNHoIHsNQA188WICrf2TMUm3Az0RmptVGELhH69RjT9vMeNhe/ujyw==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ=="}
alexa2.0 | 2023-12-27 07:42:39.594 | debug | Alexa-Cookie: Headers: {"upgrade-insecure-requests":"1","connection":"close","accept-encoding":"gzip, deflate","accept-language":"de-DE","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","user-agent":"AppleWebKit PitanguiBridge/2.2.485407.0-[HARDWARE=iPhone10_4][SOFTWARE=15.5][DEVICE=iPhone]","host":"www.amazon.com","authority":"www.amazon.com","sentry-trace":"e88d9e5fdd554eafb46e6b44ea37fca3-a965dbc43b5a8520","baggage":"sentry-environment=production,sentry-release=iobroker.alexa2%403.26.3,sentry-public_key=e9ac55f23fe149e78b1eab9ed4bf26ad,sentry-trace_id=e88d9e5fdd554eafb46e6b44ea37fca3"}
alexa2.0 | 2023-12-27 07:42:39.594 | debug | Alexa-Cookie: Proxy-Request: GET /
alexa2.0 | 2023-12-27 07:42:39.593 | debug | Alexa-Cookie: Initial Page Request: https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A454543303041343035443443313331423038303630384146434136423535383023413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=duQcrAQcc8mQv_rSJQhWzY97Zd2QlbC9HYQV04b9-rg&language=de_DE
alexa2.0 | 2023-12-27 07:42:39.593 | debug | Router: / / GET / {"host":"10.2.2.30:37781","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate","connection":"keep-alive","upgrade-insecure-requests":"1"}
alexa2.0 | 2023-12-27 07:40:57.768 | debug | Router: /favicon.ico / GET / {"host":"10.2.2.30:37781","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","accept":"image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","referer":"http://10.2.2.30:37781/","accept-encoding":"gzip, deflate","accept-language":"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6","cookie":"connect.sid=s%3AG9a_KAs_X87a0514ZLQ2XqZ0SkS8Y0-m.ugteUZ70FDHIOa%2B9hGdKFmB5F%2FEJhaXf4lwr2PxPTJs"}
alexa2.0 | 2023-12-27 07:40:57.571 | debug | [HPM] Error occurred while proxying request 10.2.2.30:37781/ to https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A454543303041343035443443313331423038303630384146434136423535383023413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=duQcrAQcc8mQv_rSJQhWzY97Zd2QlbC9HYQV04b9-rg&language=de_DE [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
alexa2.0 | 2023-12-27 07:40:57.570 | debug | ERROR: Error: connect ETIMEDOUT 31.169.123.30:443
alexa2.0 | 2023-12-27 07:40:05.282 | debug | Message: {"command":"getStatusInfo","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":716,"ack":false,"time":1703659205282},"_id":86263025}
alexa2.0 | 2023-12-27 07:40:00.172 | debug | Message: {"command":"getStatusInfo","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":715,"ack":false,"time":1703659200171},"_id":86263024}
alexa2.0 | 2023-12-27 07:39:55.138 | debug | Message: {"command":"getStatusInfo","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":714,"ack":false,"time":1703659195114},"_id":86263023}
alexa2.0 | 2023-12-27 07:38:48.342 | debug | Alexa-Cookie: Headers: {"cookie":"connect.sid=s%3AG9a_KAs_X87a0514ZLQ2XqZ0SkS8Y0-m.ugteUZ70FDHIOa%2B9hGdKFmB5F%2FEJhaXf4lwr2PxPTJs; frc=tDx9sYlY3fI+FS50sJmCOeTzENf+ckfjJ6ChZevVXgTMG2uVGOdQNHYQ3EJ+PkokBYkhQkBQUZQhIhitwNCHhsGxxH8KdbE5O/3ew8+OgGHCASVTjdu4QzfECv4ShWfklpRbu9LFK8z8F96jc9b1DyAEEo5ISSFWY4eg5+IORy0C6B+CCWxCF4kFwbt5J9czgeWsBjPQQuxEgKZrOOqaEsHjLfiGuJXgNuiK9oYpiD/OKQ79JtkR3J3w2w9HCbry0FfYhiphScy2X+R3XObtLddg12BMs+0g8IO2NCUyA72tWHceVDwoMLR2arC7DXYAxzzPsY4hdWN6NCqx8K75cOO7ksV6Sx4CdVP0R13Cb0JOrNHoIHsNQA188WICrf2TMUm3Az0RmptVGELhH69RjT9vMeNhe/ujyw==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==","accept-language":"de-DE","accept-encoding":"gzip, deflate","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","user-agent":"AppleWebKit PitanguiBridge/2.2.485407.0-[HARDWARE=iPhone10_4][SOFTWARE=15.5][DEVICE=iPhone]","upgrade-insecure-requests":"1","connection":"close","host":"www.amazon.com","authority":"www.amazon.com","sentry-trace":"e88d9e5fdd554eafb46e6b44ea37fca3-98305eae4023ef2f","baggage":"sentry-environment=production,sentry-release=iobroker.alexa2%403.26.3,sentry-public_key=e9ac55f23fe149e78b1eab9ed4bf26ad,sentry-trace_id=e88d9e5fdd554eafb46e6b44ea37fca3"}
alexa2.0 | 2023-12-27 07:38:48.342 | debug | Alexa-Cookie: Headers: {"cookie":"connect.sid=s%3AG9a_KAs_X87a0514ZLQ2XqZ0SkS8Y0-m.ugteUZ70FDHIOa%2B9hGdKFmB5F%2FEJhaXf4lwr2PxPTJs","accept-language":"de-DE","accept-encoding":"gzip, deflate","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","user-agent":"AppleWebKit PitanguiBridge/2.2.485407.0-[HARDWARE=iPhone10_4][SOFTWARE=15.5][DEVICE=iPhone]","upgrade-insecure-requests":"1","connection":"close","host":"www.amazon.com","authority":"www.amazon.com","sentry-trace":"e88d9e5fdd554eafb46e6b44ea37fca3-98305eae4023ef2f","baggage":"sentry-environment=production,sentry-release=iobroker.alexa2%403.26.3,sentry-public_key=e9ac55f23fe149e78b1eab9ed4bf26ad,sentry-trace_id=e88d9e5fdd554eafb46e6b44ea37fca3"}
alexa2.0 | 2023-12-27 07:38:48.342 | debug | Alexa-Cookie: Proxy-Request: GET /
alexa2.0 | 2023-12-27 07:38:48.320 | debug | Alexa-Cookie: Initial Page Request: https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A454543303041343035443443313331423038303630384146434136423535383023413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=duQcrAQcc8mQv_rSJQhWzY97Zd2QlbC9HYQV04b9-rg&language=de_DE
alexa2.0 | 2023-12-27 07:38:48.320 | debug | Router: / / GET / {"host":"10.2.2.30:37781","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","accept-encoding":"gzip, deflate","accept-language":"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6","cookie":"connect.sid=s%3AG9a_KAs_X87a0514ZLQ2XqZ0SkS8Y0-m.ugteUZ70FDHIOa%2B9hGdKFmB5F%2FEJhaXf4lwr2PxPTJs"}
alexa2.0 | 2023-12-27 07:38:15.180 | error | Error: Please open http://10.2.2.30:37781/ with your browser and login to Amazon. The cookie will be output here after successfull login.
alexa2.0 | 2023-12-27 07:38:15.180 | error | Error:
alexa2.0 | 2023-12-27 07:38:15.180 | debug | Error from Alexa init: Please open http://10.2.2.30:37781/ with your browser and login to Amazon. The cookie will be output here after successfull login.
alexa2.0 | 2023-12-27 07:38:15.180 | debug | Alexa-Remote: Error from retrieving cookies
alexa2.0 | 2023-12-27 07:38:15.180 | debug | Alexa-Cookie: Proxy-Server listening on port 37781
alexa2.0 | 2023-12-27 07:38:15.179 | debug | Alexa-Cookie: Error: Port 0 invalid. Use random port.
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Proxy-Mode enabled if needed: 10.2.2.30:0 to listen on 0.0.0.0
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Use as Accept-Language: de-DE
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Use as Device-App-Name: ioBroker Alexa2
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Use as Base-Amazon-URL: amazon.com
alexa2.0 | 2023-12-27 07:38:15.176 | debug | Alexa-Cookie: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Alexa-Remote: No cookie given, generate one
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Alexa-Remote: Use as Base-URL: alexa.amazon.de
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Alexa-Remote: Use as API User-Agent Postfix: iBrokAlxa2/3.26.3
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Alexa-Remote: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Update Devices Configuration Interval: 3600s
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Update Device State Interval: 309s
alexa2.0 | 2023-12-27 07:38:15.132 | debug | Update History Interval: 300s
alexa2.0 | 2023-12-27 07:38:15.131 | info | Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
alexa2.0 | 2023-12-27 07:38:15.056 | info | starting. Version 3.26.3 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.18.2, js-controller: 5.0.17
alexa2.0 | 2023-12-27 07:38:14.991 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
alexa2.0 | 2023-12-27 07:38:14.989 | debug | Plugin sentry Initialize Plugin (enabled=true)
alexa2.0 | 2023-12-27 07:38:14.970 | debug | States connected to redis: 127.0.0.1:9000
alexa2.0 | 2023-12-27 07:38:14.907 | debug | States create User PubSub Client
alexa2.0 | 2023-12-27 07:38:14.907 | debug | States create System PubSub Client
alexa2.0 | 2023-12-27 07:38:14.896 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
alexa2.0 | 2023-12-27 07:38:14.875 | debug | Objects connected to redis: 127.0.0.1:9001
alexa2.0 | 2023-12-27 07:38:14.874 | debug | Objects client initialize lua scripts
alexa2.0 | 2023-12-27 07:38:14.841 | debug | Objects create User PubSub Client
alexa2.0 | 2023-12-27 07:38:14.841 | debug | Objects create System PubSub Client
alexa2.0 | 2023-12-27 07:38:14.840 | debug | Objects client ready ... initialize now
alexa2.0 | 2023-12-27 07:38:14.822 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
alexa2.0 | 2023-12-27 07:37:22.612 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason


</body>
</html>`

**Comment by Apollon77** [comment]
Is there any Adblock, Network firewalll or whatever in place or anything else that blocks connections?

> ERROR: Error: connect ETIMEDOUT 31.169.123.30:443

means that this server can ne be reached because of network timeout.

**Comment by planetofrock** [comment]
Tried from multiple browsers and internet providers. 172.22.0.3 is not reachable. I also find it strange that it has always worked so far and there has been no connection for some time and at the same time a new registration via the IP does not work

**Comment by Draygv2** [comment]
Ow, you are a genuis. Many thanks

**Comment by Apollon77** [comment]
@planetofrock Ok what exactly is 172.22.0.3? Do you use docker? Show your alexa2 proxy configuration tab

**Comment by planetofrock** [comment]
172.22.0.3:38719 wird aufgerufen, wenn ich den Link aufrufen will 
"Bitte den [folgenden Link zur einmaligen Anmeldung im Amazon-Konto](http://172.22.0.3:38719/) nutzen, um die Adapterverbindung zu Ihren Alexa-Geräten zu aktivieren."

<html><body>

alexa2.0 | 2023-12-27 13:30:27.093 | error | Error:  Please open http://172.22.0.3:38719/ with your browser and login to  Amazon. The cookie will be output here after successfull login.
-- | -- | -- | --
alexa2.0 | 2023-12-27 13:30:27.092 | error | Error:
alexa2.0 | 2023-12-27 13:30:26.438 | info | Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
alexa2.0 | 2023-12-27 13:30:26.396 | info | starting. Version 3.26.3 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.13.0, js-controller: 4.0.24


</body>
</html>

**Comment by Apollon77** [comment]
Dann ist 172.22.0.3 die lokale IP des iobroker servers ... Warum diese scheinbar von deinem Browser aus nicht erreichbar ist musst Du wissen :-) Wie rufst DU denn admin auf? Diese IP/Hostname muss in die Proxy Konfig vom alexa 2 adapter wenn du so eine konstellation hast. Oder der Proxy port miss freigeschaltet werden ... Am besten poste mal im ioBroker Forum für Support dazu.
