### ISSUE TITLE
No 'speak' output on multiroom devices

### ISSUE THREAD

**Issue by 1Cliff** [Apollon77/ioBroker.alexa2#170]
The 'speak' output will not work on any of my multiroom groups.
Single devices work well.
I already reloaded the adapter.
Within the 'devices' i set the volume to 55 (Like my single devices).
I can see the textstring appearing in the 'speak'property, but nothing happens.
No error messages from Alexa or IoBroker....

**Comment by Apollon77** [comment]
Turn on debug log and send debug of such a multiroom speak please.

**Comment by 1Cliff** [comment]
Here it is. I removed my account- details (Hopefully ;) ).
Job: 
- IoBroker is triggered by Alexa routine.
- IoBroker counts open doors and windows 
- IoBroker asks Alexa to tell this to multiroom 'house'

[iobroker.zip](https://github.com/Apollon77/ioBroker.alexa2/files/2698048/iobroker.zip)

**Comment by Apollon77** [comment]
Ok, according to the log the requests are sended to the devices and also show up in the history that is requested. So from a API side of things it looks ok.

Please also check the languages of the alexa devoces ... are they set to german? Because the speak is send out as germany and we had reports that when language do not match then some times speak was not output.

Please also check if speach output is possibel using an own created routine. If this works please send debug log of invoking this routine via iobroker

**Comment by Apollon77** [comment]
kann es nicht nachvollziehen, klappt bei mir ... Bitte mit 2.1 vom Github nochmals versuchen
