### ISSUE TITLE
Door sensor device not triggering

### ISSUE THREAD

**Issue by stuermera** [Apollon77/ioBroker.alexa2#236]
Hi there!

I have 2 pcs. TUYA door sensors. 
Both are connected with my Alexas too - it even works without problems to let Alexa say "Door X is now open" - it gets recognized 2-3 seconds after the door sensor has been triggered.

But I can't get it work with ioBroker/Homekit.
I am using the sensor state "detectionState" (false = closed, true = open).
But when opening a door, the value doesn't change to "true" even my Alexa tells me the door is now open.

![sensor](https://user-images.githubusercontent.com/11447150/57518316-08c4c280-7319-11e9-99a4-2d13086d0f73.JPG)

Any idea?
Since Alexa is recognizing the trigger, it has to be somehow stored I think.

Thanks.

**Comment by Apollon77** [comment]
The device is not online long enough that the adapter can initiate a communication. So only the tuya Cloud has the Info ... and so also Alexa skill. So no Chance For now via this adapter. Sorry

**Comment by Apollon77** [comment]
Sorry, anwer is wrong ( i was confused about the tuya). But reason here is that Alexa2 Adapter is not getting push infos from Amazon, but needs to fetch the data, so you need to trigger #query in order to update the values ... but this is limited, so you will never get a "real time" info in the adapter, sorry for now

**Comment by stuermera** [comment]
Hi @Apollon77 - Thanks.
That's right - there's a manual switch _#query_ which sometimes is able to read the detectionState value. But not always. If "never get realtime" means a few minutes later it would be OK.
What are the possibilities to automatically trigger this query?
Thanks.

**Comment by Apollon77** [comment]
The problem is that each "query" triggers a request to Amazon APIs to fetch the current values, if they do not know the state then they will trigger a request to the tuya skill in this case. There exists some rate limiting limitations from Amazon side ... so it may work if you have one such sensor to request the status once a minute. I think the adapter currectly have a 5 or 10 mins limit included to prevent spamming. This may be configurable in next version. So for now: if you create a javascript triggering the "#query" every 5 mins shoudl work ... but this do not really scale with many such sensors

**Comment by stuermera** [comment]
Thanks, will try it with JS/Blockly today... :)
