### ISSUE TITLE
Exception: native.valueMap.indexOf is not a function

### ISSUE THREAD

**Issue by dklinger** [Apollon77/ioBroker.alexa2#291]
Hi,
adapter keeps restarting with the exception mentioned in the subject.
Enabling the debug logs points to this line: https://github.com/Apollon77/ioBroker.alexa2/blob/6bb5fb6612078f08f81529c1f0da93603460c0fa/main.js#L748
The last output prior to getting the exception is "Get Index for Value "Alexa.ColorTemperatureController.[....]", so the line makes sense. 
I don't know the background of this line, but maybe a check if valueMap exists on this object or if it is of type "function" would be sufficient.

Regards,
Daniel

**Comment by Apollon77** [comment]
In fact it seems that amazon return unexpected data. The method you found is used very generic. So yes a check for valueMap could help but it would be great to know the reason too

So please post the fullstack trace of the error. And send the full log of an adapter start up to the crash to iobroker@fischer-ka.de and I will check it in detail. But this will take some days.

**Comment by dklinger** [comment]
Hi, 

here's the Stack Trace. The log is coming in the next minutes via mail. 

Thanks for looking into it. My guess is, that it's a problem with the brightness of the IKEA-Lamp which is connected via deconz which emulates a hue bridge...

**Comment by Apollon77** [comment]
auch 743:32

**Comment by dklinger** [comment]
Wie meinen?

**Comment by Apollon77** [comment]
In einem anderen log gab es den gleichen Fehler auch in der anderen Zeile.

**Comment by dklinger** [comment]
Kannst du mir das log zukommen lassen? Dann würde ich mir das mal ansehen. Derselbe Fehler macht bei 743:32 nicht viel Sinn. Bezieht sich das andere Log ggf. auf einen älteren Code-Stand?

**Comment by Apollon77** [comment]
Das kann sein. Dann fixen wir das.

**Comment by amnesia106** [comment]
Auf Version 2.6.4 bekomme ich den Fehler auch.

**Comment by dklinger** [comment]
Jup, auf der Version bin ich ja auch. Mein "fix" basiert auch genau auf der.

**Comment by sissiwup** [comment]
`host.zotac	2019-09-18 22:42:56.772	info	Restart adapter system.adapter.alexa2.0 because enabled
host.zotac	2019-09-18 22:42:56.772	error	instance system.adapter.alexa2.0 terminated with code 0 (OK)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at endReadableNT (_stream_readable.js:1125:12)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at IncomingMessage.emit (events.js:194:15)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at IncomingMessage.res.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:752:58)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at alexa.querySmarthomeDevices (/opt/iobroker/node_modules/iobroker.alexa2/main.js:607:13)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at updateSmarthomeDeviceStates (/opt/iobroker/node_modules/iobroker.alexa2/main.js:792:46)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[2]: 2019-09-18 22:42:56.748 - alexa2.0 TypeError: native.valueMap.indexOf is not a function
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[1]: 2019-09-18 22:42:56.748 - alexa2.0 uncaught exception: native.valueMap.indexOf is not a function
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at endReadableNT (_stream_readable.js:1125:12)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at IncomingMessage.emit (events.js:194:15)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at IncomingMessage.res.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:752:58)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at alexa.querySmarthomeDevices (/opt/iobroker/node_modules/iobroker.alexa2/main.js:607:13)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at updateSmarthomeDeviceStates (/opt/iobroker/node_modules/iobroker.alexa2/main.js:792:46)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37)
host.zotac	2019-09-18 22:42:56.772	error	Caught by controller[0]: TypeError: native.valueMap.indexOf is not a function
alexa2.0	2019-09-18 22:42:56.753	error	TypeError: native.valueMap.indexOf is not a function at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37) at updateSmarthomeDeviceStates (/opt/iobroker/node_modules/iobr
alexa2.0	2019-09-18 22:42:56.753	error	uncaught exception: native.valueMap.indexOf is not a function
alexa2.0	2019-09-18 22:42:56.753	warn	Exception: TypeError: native.valueMap.indexOf is not a function
mqtt.0	2019-09-18 22:42:49.717	info	Client [klingel-se-51] connection closed: closed
alexa2.0	2019-09-18 22:42:46.802	info	Alexa-Push-Connection established. Disable Polling
alexa2.0	2019-09-18 22:42:41.231	info	starting. Version 2.6.4 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.15.3`

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by dklinger** [comment]
Thanks. Will test it after the holidays. 👍

**Comment by dklinger** [comment]
Läuft jetzt wieder einwandfrei. Danke dir!
