### ISSUE TITLE
Alexa objects containing '#' and mqtt

### ISSUE THREAD

**Issue by KoffeinKaio** [Apollon77/ioBroker.alexa2#301]
Hey there,

I dont know if its a Bug of the Mqtt adapter, a Bug of the Alexa adapter or just general incompatibility.

Mqtt doesnt allow '#' and '+' in topic names because they are used as wildcard characters.
Since the Adapter is naming some objects '#trigger' and so on, sending the data of this adapter to mqtt will cause a disconnect of the session.

How could this be resolved? I really would like some alexa data available in mqtt.

Link to mqtt-adapter-issue: https://github.com/ioBroker/ioBroker.mqtt/issues/65#issue-498763909

**Comment by Apollon77** [comment]
In general "'" is an allowed character in iobroker, so I would see a handling of such a "protocol specific not allowed character" in that protocol implementation ... So we should fix mqtt

**Comment by KoffeinKaio** [comment]
I dont think names with '+', ' / ' or '#' are valid standard as they are used to wildcard filter something.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349842

**Comment by Apollon77** [comment]
I see your point, for now ther eis a list of forbidden characters for ioBroker objects IDs ... and "#" is not on that list, so regarding "how an adapter can name it's states" it is allowed.

How we now handle such a case in MQTT adapter we need to see ... beside "not sendiung" would could also replace it by "__HASH__" or "%%HASH%%" because this conversion works in both directions when we asume that noone names Objects like this ... so there are ways to bring the systems together.

In such a highly "inter-connected world" like ioBroker it is impossible to sync allowed characters between all protocols and  systems (or we end in Characters only) ;-)

**Comment by KoffeinKaio** [comment]
You are right in that case, it IS allowed, just not usable in mqtt :(

Converting it was also on my list of Ideas, good point. That would be the best way to keep functionality. So the mqtt adapter is the right place for it, got it.
