### ISSUE TITLE
I am getting ''null'' and ''invalid ''in status of card

### ISSUE THREAD

**Issue by MattL0** [Apollon77/ioBroker.alexa2#384]
I think maybe amazon changed their api?

![Capture](https://user-images.githubusercontent.com/27497561/75204901-33fd8e80-5740-11ea-9d8f-1d529c5e3a58.PNG)
It is getting hard to be understood by amazon since 1-2 weeks

**Comment by Apollon77** [comment]
Hm ... the Adapter is only providing the values returned by amazon. Sorry but what should I do? ;-)

**Comment by MattL0** [comment]
I really do not know . Sorry for this lol. 


Maybe integrate in iobroker parsed data (based on echo device ), and filter empty content, and allow only the requests  make sense allow.

I also think that in push mode , the plugin here do not catch all the update from what is beeing said to an alexa device ? Maybe there is something with the websocket connection?

**Comment by Apollon77** [comment]
These states are exactly thought to pass the data from amazon to the users ... so you need to be able to handle all (undocumented) avuers amazon provides there if you use this field ... 

There is currently an issue (#371) with rate limiting where anmazon seemed to have changed stuff ... I'm rewritug that "summary" management at the moment. maybe it also has something to do with this. Bit even then the data will come that way because they were returned by amazon that way. The fix will just make sure nothing is forgotten.

**Comment by MattL0** [comment]
Thank you!

Sent from an Iphone
________________________________

**Comment by MattL0** [comment]
I will translate this topic when i get home

Sent from an Iphone
________________________________

**Comment by MattL0** [comment]
I sould have read that topic.. before posting !!
