### ISSUE TITLE
Disabling some commands for device because of unknown type

### ISSUE THREAD

**Issue by CrEaK** [Apollon77/ioBroker.alexa2#56]
There are the following log-entries after starting the adapter:
`
Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
Device-type:A1J16TEDOYCZTN (PEONY,MICROPHONE,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,ASX_TIME_ZONE,REMINDERS)
`
I looked into the objects and this is the device:
![image](https://user-images.githubusercontent.com/513850/43708680-4d40c126-996b-11e8-884b-8007ba12fbd5.png)

I have no idea where this device comes from, maybe from just development test with the alexa api, where i was fooling around :D

EDIT: I found the device type: Its my FIRE 7 Tablet :)

**Comment by Apollon77** [comment]
what exactly you can do with this device and routines? Can you use it to speak text or such?

**Comment by Apollon77** [comment]
check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095

**Comment by CrEaK** [comment]
good question. I think the alexa integration in the fire tables are fairly new. I will have a quick look this evening and will report back :+1:

**Comment by Apollon77** [comment]
I added including commands in 0.4.0 ... tell me if I should deactivate commands because not working :-)

**Comment by Chaot1** [comment]
Aktuell habe ich plötzlich den gleichen Fehler:
`

alexa2.0 | 2018-12-02 18:41:15.198 | warn | Device-type:A1C66CX2XD756O (PERSISTENT_CONNECTION,ASX_TIME_ZONE,SUPPORTS_SOFTWARE_VERSION,REMINDERS,MICROPHONE,PEONY,TIMERS_AND_ALARMS,VOLUME_SETTING)
-- | -- | -- | --
alexa2.0 | 2018-12-02 18:41:15.198 | warn | Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

`
Vermutlich im Zusangenhang mit dem Update auf JS 4.01

**Comment by hawi1981** [comment]
Bei mir auch und das ca. alle 2 Minuten. Macht meinen Log sehr voll:


alexa2.0 | 2019-01-21 10:45:59.927 | warn | Device-type:A3B50IC5QPZPWP  (KINDLE_BOOKS,AUDIBLE,AMAZON_MUSIC,TIMERS_AND_ALARMS,GOLDFISH,SLEEP,PERSISTENT_CONNECTION,MUSIC_SKILL,CHANGE_NAME,AUDIO_PLAYER,DEREGISTER_DEVICE,MICROPHONE,SUPPORTS_CON
-- | -- | -- | --
alexa2.0 | 2019-01-21 10:45:59.925 | warn | Disabling some commands for device because of unknown type. Report to  developer as GitHub issue with details for device. Please grab full next  line pot. from logfile on disk if cutted
alexa2.0 | 2019-01-21 10:45:59.912 | warn | Device-type:AKOAGQTKAS9YB  (NO_UNITS_AND_TIMEZONES,CHANGE_NAME,DEREGISTER_DEVICE,PERSISTENT_CONNECTION,MICROPHONE,PEONY,UPDATE_WIFI,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,BLOWER)
alexa2.0 | 2019-01-21 10:45:59.911 | warn | Disabling some commands for device because of unknown type. Report to  developer as GitHub issue with details for device. Please grab full next  line pot. from logfile on disk if cutted
alexa2.0 | 2019-01-21 10:44:05.744 | warn | Device-type:A3B50IC5QPZPWP  (KINDLE_BOOKS,TUNE_IN,CHANGE_NAME,I_HEART_RADIO,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MUSIC_SKILL,TIMERS_AND_ALARMS,SLEEP,DEREGISTER_DEVICE,VOLUME_SETTING,AUDIO_PLAYER,DRE
alexa2.0 | 2019-01-21 10:44:05.743 | warn | Disabling some commands for device because of unknown type. Report to  developer as GitHub issue with details for device. Please grab full next  line pot. from logfile on disk if cutted
alexa2.0 | 2019-01-21 10:44:05.737 | warn | Device-type:AKOAGQTKAS9YB  (SUPPORTS_SOFTWARE_VERSION,BLOWER,DEREGISTER_DEVICE,VOLUME_SETTING,CHANGE_NAME,UPDATE_WIFI,PEONY,PERSISTENT_CONNECTION,NO_UNITS_AND_TIMEZONES,MICROPHONE)
alexa2.0 | 2019-01-21 10:44:05.736 | warn | Disabling some commands for device because of unknown type. Report to  developer as GitHub issue with details for device. Please grab full next  line pot. from logfile on disk if cutted

**Comment by Apollon77** [comment]
Und es macht Sinn an ein geschlossenes Issue was neues dran zu hängen? :-(
