### ISSUE TITLE
Tuya states not passed to ioBroker

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#589]
Hi, I have two Tuya devices present in the Alexa app. The states are reflected perfectly fine (door & motion sensor). Nevertheless the states aren't passed on to the corresponding iobroker object. Can this be fixed?

**Comment by Apollon77** [comment]
Please provide a full debug log (Instances - Expert mode - column loglevel) from adapter start and querying these devices. Logfile needs to be taken from logfile on disk and NOT admin. Send then with reference to this issue to iobroker@fischer-ka.de

**Comment by JanWeskamp** [comment]
@Apollon77 
Hi there i have the same problem .... tried to set 2 switches active if the third is pressed but script cant catch any change.... i looked for issues of my script and reinstall 4 times but then i checked the states.... nothing worked even manualle intervall cant get actual changes

**Comment by JanWeskamp** [comment]
> @Apollon77
> Hi there i have the same problem .... tried to set 2 switches active if the third is pressed but script cant catch any change.... i looked for issues of my script and reinstall 4 times but then i checked the states.... nothing worked even manualle intervall cant get actual changes


alexa2.0 | 2020-12-06 03:37:07.333 | info | (87898) Subscribing to states...
-- | -- | -- | --
alexa2.0 | 2020-12-06 03:37:07.075 | info | (87898) Alexa-Push-Connection established. Disable Polling
-- | -- | -- | --
alexa2.0 | 2020-12-06 03:37:04.029 | info | (87898) starting. Version 3.3.5 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.20.0, js-controller: 3.1.6
alexa2.0 | 2020-12-06 03:37:04.013 | info | (87898) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

**Comment by Apollon77** [comment]
Aahhhh ... If you expect that the adapter is getting the info automatically then this is not the case. There is no "smart devie change push" to the adapter because amazon is not doing that, so "Polling" is the only way. means: "#query" state.
Sorry to use Alexa2 to get an realtime update for a motion sensor or such is not working.
Alexa App is ding this polling when you are on that one particular device page in the app

**Comment by JanWeskamp** [comment]
Nooo the powerstate never changes in my case ...-.- the device shown an old state ...... no matter if pull or push

**Comment by Apollon77** [comment]
No, the linked log with "disable polling" is something completely different and only relevant for music-data, volume and "device interactions". Smart devices are ALWAYS polling via the "#query" state ONLY

**Comment by JanWeskamp** [comment]
@Apollon77 
So then could you maybe explain me why i can't get closer realtime data? Sorry for asking maybe dump questions but i want to set 2 switches active if i hit another ... Problem here i have to wait 1 min+ before the state changes

**Comment by JanWeskamp** [comment]
![Bildschirmfoto 2020-12-07 um 02 20 24](https://user-images.githubusercontent.com/21228831/101301712-f9ca2d00-3839-11eb-867c-218b23402bc0.png)

**Comment by Apollon77** [comment]
It is easy. Polling data will get data from amazon lambda functions. At least sometimes. This computing time is payed by the skill developer.

Constantly polling if kind of all states will generate huge costs for the skill developer and will also run very fast into amazon rate limits (query ONE state like the app for a limited time works maybe ... but not many). That's why I decided that this will not be offered by the adapter - else the risk that Amazon closes these ways is too high.

**Comment by Apollon77** [comment]
You could try to create via iot adapter a virtual device that points to a JavaScript object in iobroker and create then a routine/scene on amazon side that witches that device on movement of the detector device or such. So you gets real-time trigger into iobroker to react on
