### ISSUE TITLE
Neue Funktion: Kamera Live Video

### ISSUE THREAD

**Issue by n3ucr0n** [Apollon77/ioBroker.alexa2#656]
Hallo,

ich habe heute entdeckt, dass ich über de Alexa App, live auf die Kamera meiner Türklingel zugreifen kann (in meinem Fall ein Ring Doorbell 3 Plus)

könnte man diese Funktionalität dem „Smart Home Devices“ Datenpunkt der Ring Doorbell hinzufügen um den das Videobild für die VIS zu verwenden?

Danke und liebe Grüße.

Micha

**Comment by Ilovegym66** [comment]
Hi, wollte die Tage schon ein issue aufmachen.
Hier ein paar Screenshots aus der App:

![Screenshot_20210321-213550_Amazon Alexa](https://user-images.githubusercontent.com/36229898/111920151-bebcd400-8a8d-11eb-9d95-394abd9cbe70.jpg)
![Screenshot_20210321-213612_Amazon Alexa](https://user-images.githubusercontent.com/36229898/111920156-c7150f00-8a8d-11eb-880f-791a9b0d29e4.jpg)
![Screenshot_20210321-213628_Amazon Alexa](https://user-images.githubusercontent.com/36229898/111920157-caa89600-8a8d-11eb-8499-7b0205e5b077.jpg)

**Comment by Apollon77** [comment]
In fact the issue is more that I need to get such a thing or someone of you needs to do a proxy capture of the relevant traffic. I fsomeone is up for that just tell and I tell you how

**Comment by n3ucr0n** [comment]
> In fact the issue is more that I need to get such a thing or someone of you needs to do a proxy capture of the relevant traffic. I fsomeone is up for that just tell and I tell you how

With an appropriate instruction (I am really beginner) I would try it.

**Comment by Ilovegym66** [comment]
proxy from the phone with the app .. ?? or a wireshark log ? 
I have time the next days to support you..

**Comment by Apollon77** [comment]
For proxy please use CharlesProxy. I do all with this and works great! https://www.charlesproxy.com/download/

Download an install, start and is acts as a proxy on port 8888. Add that as proxy to your wlan connection in your mobile device.
Then register the charles proxy ssl root cert (follow instructions https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) and activate it (two places where you need to activate it in ios, android a bit different). Then in Charles you also need to enable SSL Proxying. Then you should get that traffic. Import is that you do not just see "CONNECT" requests in charles, but actually real GET/POST/... requests and data

Now start the alexa app and also sgtart  therecording session in charles. Then best navigate to the camera relevant settings and also place where camera is displayed and such.
Ideally also add time infos when you did what and maybe done some pause between, so that IO can better see what requests belog to what.

End charles session. remove all unwanted traffic the proxy catched too. Send me the chls file via email to iobroker@fischer-ka.de

**Comment by Ilovegym66** [comment]
this sounds very good and easy to install and use, thank you! 
I can use this for other projects and adapters, too.. 
it's in progress...

**Comment by Ilovegym66** [comment]
first tests withc charles and alexa app are failed - error if I in the setup of a device 'da ist etwas schiefgelaufen' ... keine Verbindung..
I test tomorrow again..

**Comment by Apollon77** [comment]
Then check Proxy and Cert again if correctly enabled and such

**Comment by Ilovegym66** [comment]
I send you something per mail now.. :-)

**Comment by Apollon77** [comment]
As sent via email the camera stream seems to be started via TCP directly ... so no way to catch via proxy. :-(

**Comment by Apollon77** [comment]
Please provide a new full debug log with the GitHub version (soon 3.14) ...

**Comment by Apollon77** [comment]
AFter other tries there seems to be no real way for now to get that ... maybe a Charles proxy thing gives insights but it seems to be done like a "video call" and this would then also not work out
