### ISSUE TITLE
Values not updated

### ISSUE THREAD

**Issue by cactus-online** [Apollon77/ioBroker.alexa2#711]
I'm using the adapter to bring my ZigBee devices, connected to EchoStudio-ZigBee-Hub, to ioBroker. 
The Problem is, if I change for example the brightness in the ioBroker, this is immediately transmitted to Alexa. If I change the brightness in the Alexa app, the value does not arrive in the ioBroker.
Push-Connect is enabled.
Any hints ?

**Comment by Apollon77** [comment]
What exactly you mean? Alexa 2 has nothing to do with controlling of devices. Or do you mean that if you change an "iobroker smart device state" then it is done but the "ALexa2 smart device state do not get updated automatically"? If yes thsi si intended and the case for ALexa 2 because amazon has no push info pon smart homemdevice changes ... so thats why there is that "#query" state in alexa2 ... but honestly: why you check alexa2 if you have the device in iobroker in zigbee adapter? That makes no sense

**Comment by cactus-online** [comment]
Do you know, how to integrate EchoPlus ZigBee Hub into ioBroker in an other way than alexa2 Adapter?

**Comment by Apollon77** [comment]
Ahhhhh the zigbee devices connected to the EchoPlus directly ... ok got it.

But in fact it is the same issue: Amazon offers no "push info" on "device state changes", so the adapter would need to request the state for ALL states in a polling mechanism, but in fact queriyuíng the device status uses amazon cloud and so all skill providers are queried ... this generates high costs for all of them. So this i sno option.

This means: Yes you can see the state, you can manually "query" it using #query (but in limited intervals), but thats all. Sorry, nothing more possible technically

**Comment by cactus-online** [comment]
OK, understand. I wonder me, how is the Alexa App doing this. Because here the state ist up-to-date.
As read in log, it uses mqtt, which is in imho the right protocoll for this and capable for such bedirectional communication.

Maybe you can add a pull option for a limit number of smart devices ? Or is this, what you mean with „using #query“ ? How to do this?

**Comment by cactus-online** [comment]
I agree, best way would be communicate to the ZigBee-Hub on the Echo locally.

But the protocol/api at ZigBee on Echo is not open or no interface existing, right?

**Comment by Apollon77** [comment]
> I wonder me, how is the Alexa App doing this. Because here the state ist up-to-date.

It requests the data as soon as you open the page of the device ... so it polls the data then when you want to see it

> As read in log, it uses mqtt,

Which log? Where it uses mqtt? Or do you mean that alexa 2 says it is "wsmqtt"? If yes then ignore ... We named it that way as we discovered it. It is "like MQTT via a websocket" from the protcol level, but it is unidirectional and it comes from amazon ... how should we be able to enhance it??

> Maybe you can add a pull option for a limit number of smart devices 

No I will not do that. Too many users created too many traffic for all kind of smart devices in the past "just because it was possible" with ignoring that it might cost a lot of money for the skill provider. Thats why I will protect the Alexa2 adapter because there is a high chance that Amatzin will actively prevent it if we overuse it "just because we can" ... so ... no

No APIs are open.

Honestly: Get a Zigbee stick and move the devices to that Stick and iobroker and then control via iot and alexa ... then you have all control you want :-))

**Comment by Apollon77** [comment]
> OK, if it causes cost and no one pays for it, understandeable that you‘re not willing to that.

No you get me wrong. Not costs on my side ... costs of the side of the company that operated the Skill where the device is connected. Ok for the Zigbee Hub it is kind of Amazon itself but for other devices it are the Skill owners.

>  But are you sure it‘s unidirect? If the Alexa App is open, and I switch off the lamp in ioBroker, the status immediately synchronized in the Alexa-App... . Maybe not opend for 3rd parties by Amazon.

When you set a value and the command response is ok then you know the status - you do not need to ask someone normally. But also the adapter asksa for the status after a "set" action ... this is ok. So nothing to compare here.
Try one thing: Open the app on the screen where you see the status of a device. Now use your voice to your echo to change the state ... Does the app get that update immediately? If yes this is a new feature I never saw ... I expect it only updates if you reload thet page in the app.

> There is another issue. Changing the brightness in ioBroker, the lamp follows (for a short moment) and than a new brightness is set up between the original value and new adjusted value, without any action at me. Example: Original value is 20, changend in ioBroker to 90, lamp is bright (for around a second) than it changes to 58 automatically (not the same value at different tries, it‘s random).

No idea ... you mean "changing in iobroker" that you change using alexa2? No idea what happens in the background on Amazon side here that could cause this. Sorry.

You need to understand that nothing of this is official amazon APIs. The adapter uses knowledge gained by reverse engineering what they do in their Alexa App and kind of mirroting this behaviour. So we are limited to what the App can do because we do not know more then that

**Comment by cactus-online** [comment]
That‘s true. If I say „Alexa schalte Küche Unterschrank ein.“ light is on and the state in the Alexa App on the mobile is also changend to on. Same behaviour if instead saying „Alexa ...“ I change the power state of the power object of the lamp at the Alexa2 subtree at ioBrokers Object tree.

**Comment by Apollon77** [comment]
I can check again,. but most likely they poll iton their side in the app only that one state :-)

**Comment by cactus-online** [comment]
Can I do something for help ?

**Comment by Flacedoo** [comment]
I face the same issue - I've got flush mounted zigged switches installed behind my normal switches. Now I want to turn on a second lamp whenever this switch has changed its state. Isn't there anything we could do besides moving all the zigbee devices to a new hub which support push notifications?

**Comment by Apollon77** [comment]
As said - from current knowledge the app is polling the single device which is displayed in the app. So it gets udates fast. There is still no push mechanism. This way is simply not suitable to get real time updates, sorry guys

**Comment by cactus-online** [comment]
It is as it is. But trust me, when the Alexa-App uses polling, then it polls at least every second. Changes at ZigBee-devices connected to my Echo Studio made with alex2 are immediately displayed in Alex-App. 
I think it's OK to say, Alex2 will/or can not support this. Thenever I don't believe that Alexa App uses polling ;-). My opinion.

**Comment by Apollon77** [comment]
> Thenever I don't believe that Alexa App uses polling 

Honestly: Then we need to find it out, but I need your support because I do not have such an Alexa device that has a zigbee hub included.

So:
* Install Charles Proxy on a computer in the same network
* Configure it to also capture ssl traffic (ssl proxying)
* install the Charles proxy certificate on your mobile phone (see https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/)
* Check that you get traffic (if you only see "CONNECT" clls in charles then something is not setup corectly with the ssl proxying
* then start a recording session
* open Alexa App
* open such a device page and do a change outside of the app, note the time when this happened

Then save the reconding file and sent it to me email to iobroker@fischer-ka.de with info that it belongs to this issue (include link pelase). Ad dthe time infos when happened what ... Then I have a look and we know for sure

**Comment by Apollon77** [comment]
Ok, I git a log and as expected: The App is constantly polling the device status any 3s... This works for one device , but not in a "all device matter" like the adapter works. Sorry guys
