### ISSUE TITLE
Adapter not working after Upgrade to 3.10.4

### ISSUE THREAD

**Issue by SKB-CGN** [Apollon77/ioBroker.alexa2#764]
Hi,
the adapter is not working anymore.
I have Node-JS: v14.18.0 installed

**Comment by StefCGN** [comment]
Hi,
here is the Log Set:
<html><body>


alexa2.0 | 2021-10-11 12:18:42.823 | error | adapter disabled
-- | -- | -- | --
alexa2.0 | 2021-10-11 12:18:42.515 | debug | Plugin sentry Initialize Plugin (enabled=true)
host.ioBroker | 2021-10-11 12:18:14.049 | info | "system.adapter.alexa2.0" disabled
host.ioBroker | 2021-10-11 12:18:10.468 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker | 2021-10-11 12:18:10.467 | info | instance system.adapter.alexa2.0 terminated with code NaN ()
host.ioBroker | 2021-10-11 12:18:10.465 | warn | instance system.adapter.alexa2.0 terminated due to SIGBUS
alexa2.0 | 2021-10-11 12:18:10.052 | debug | Alexa-Remote  WS-MQTT: Incoming RAW message:  307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
alexa2.0 | 2021-10-11 12:18:10.046 | debug | Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.de/tcomm/
alexa2.0 | 2021-10-11 12:18:09.572 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/behaviors/entities?skillId=amzn1.ask.1p.music","method":"GET","timeout":10000,"headers":{"Routines-Version":"1.1.210292"}}
alexa2.0 | 2021-10-11 12:18:09.571 | debug | Alexa-Remote: No authentication check needed (time elapsed 3073)
alexa2.0 | 2021-10-11 12:18:09.540 | debug | Alexa-Remote: Initialize WS-MQTT Push Connection
alexa2.0 | 2021-10-11 12:18:09.537 | debug | Alexa-Remote: Response: {"notifications":[]}
alexa2.0 | 2021-10-11 12:18:08.886 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/notifications?cached=true&_=1633947488886","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:08.886 | debug | Alexa-Remote: No authentication check needed (time elapsed 2387)
alexa2.0 | 2021-10-11 12:18:08.883 | debug | Alexa-Remote:  Response:  {"bluetoothStates":[{"deviceSerialNumber":"9b152b51d8704399bfc1b33db9fa8214","deviceType":"A2TF17PFR55MTB","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"130050002","streamingState":null},{"deviceSerialNumber":"SMG950FF40469E1060EB598","deviceType":"A1DL2DVDQVK3Q","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"516110110","streamingState":null},{"deviceSerialNumber":"70940514603302JH","deviceType":"ADVBD696BHNV5","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"662663720","streamingState":null},{"deviceSerialNumber":"edbb7e932cf347c7b287a5db19c3ee30","deviceType":"A3C9PE6TNYLTCH","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"0","streamingState":null},{"deviceSerialNumber":"G0911X03941304ML","deviceType":"A2JKHJ0PX4J3L3","friendlyName":"FireTV","gadgetPaired":false,"online":true,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"21039196292","streamingState":null},{"deviceSerialNumber":"G0911M079406180P","deviceType":"A1RABVCI4QCIKC","friendlyName":"Echo   Dot-80P","gadgetPaired":false,"online":true,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"5805753220","streamingState":null},{"deviceSerialNumber":"G090U610916420KJ","deviceType":"A32DOYMUN6DTXA","friendlyName":"Echo-0KJ","gadgetPaired":false,"online":true,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"5805753476","streamingState":null},{"deviceSerialNumber":"G09183091056058K","deviceType":"A1Z88NGR2BK6A2","friendlyName":"Echo   Show","gadgetPaired":false,"online":true,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"5805754756","streamingState":null},{"deviceSerialNumber":"21c59241ed82e98a939e5f47592a8d7e","deviceType":"A2IVLV5VM2W81","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"1","streamingState":null},{"deviceSerialNumber":"SMG985F5B8874995CD23CCC","deviceType":"A1DL2DVDQVK3Q","friendlyName":null,"gadgetPaired":false,"online":false,"pairedDeviceList":null,"sconeBattery":null,"sconePaired":false,"softwareVersion":"516140110","streamingState":null}]}
alexa2.0 | 2021-10-11 12:18:08.181 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/bluetooth?cached=true&_=1633947488181","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:08.180 | debug | Alexa-Remote: No authentication check needed (time elapsed 1682)
alexa2.0 | 2021-10-11 12:18:08.178 | debug | Alexa-Remote:  Response:  {"wakeWords":[{"active":true,"deviceSerialNumber":"G0911X03941304ML","deviceType":"A2JKHJ0PX4J3L3","midFieldState":null,"wakeWord":"ALEXA"},{"active":true,"deviceSerialNumber":"G0911M079406180P","deviceType":"A1RABVCI4QCIKC","midFieldState":null,"wakeWord":"ALEXA"},{"active":true,"deviceSerialNumber":"G090U610916420KJ","deviceType":"A32DOYMUN6DTXA","midFieldState":null,"wakeWord":"ALEXA"},{"active":true,"deviceSerialNumber":"G09183091056058K","deviceType":"A1Z88NGR2BK6A2","midFieldState":null,"wakeWord":"ALEXA"}]}
alexa2.0 | 2021-10-11 12:18:07.799 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/wake-word?_=1633947487798","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:07.798 | debug | Alexa-Remote: No authentication check needed (time elapsed 1300)
alexa2.0 | 2021-10-11 12:18:07.795 | debug | Alexa-Remote:  Response: {"devices":[{"accountName":"This  Device","appDeviceList":[{"deviceAccountId":"A0861997DUI3R74CCS7X","deviceType":"A2TF17PFR55MTB","serialNumber":"9b152b51d8704399bfc1b33db9fa8214"}],"capabilities":["ADAPTIVE_LISTENING","TIMERS_AND_ALARMS","MICROPHONE","SOUND_SETTINGS","REMINDERS","DIALOG_INTERFACE_VERSION","VOLUME_SETTING","CUSTOM_ALARM_TONE"],"charging":null,"clusterMembers":[],"deviceAccountId":"A0861997DUI3R74CCS7X","deviceFamily":"VOX","deviceOwnerCustomerId":"A1EIP8DVPCTVOF","deviceType":"A2TF17PFR55MTB","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"9b152b51d8704399bfc1b33db9fa8214","softwareVersion":"130050002"},{"accountName":"Marijana's  Alexa  Apps","appDeviceList":[{"deviceAccountId":"A06654591OVZOCDFF8ZR0","deviceType":"A1DL2DVDQVK3Q","serialNumber":"SMG950FF40469E1060EB598"},{"deviceAccountId":"A01169689K3RKDK3Z6UV","deviceType":"A1DL2DVDQVK3Q","serialNumber":"SMG980F682BCDDF422ED90F"},{"deviceAccountId":"A024247128CGZ5KLLWDXY","deviceType":"A1DL2DVDQVK3Q","serialNumber":"SMT8134A745230E200CDB9"}],"capabilities":["ADAPTIVE_LISTENING","MICROPHONE","VOLUME_SETTING"],"charging":null,"clusterMembers":[],"deviceAccountId":"A06654591OVZOCDFF8ZR0","deviceFamily":"AMAZONMOBILEMUSIC_ANDROID","deviceOwnerCustomerId":"A1EIP8DVPCTVOF","deviceType":"A1DL2DVDQVK3Q","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":false,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"SMG950FF40469E1060EB598","softwareVersion":"516110110"},{"accountName":"Stephan's  Fire TV  stick","appDeviceList":[],"capabilities":["ADAPTIVE_LISTENING","ASCENDING_ALARM_VOLUME","SUPPORTS_LOCALE","MICROPHONE","PERSISTENT_CONNECTION","SHARKNADO","CHANGE_NAME","VOLUME_SETTING","CUSTOM_ALARM_TONE","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","FLASH_BRIEFING","ACTIVE_AFTER_FRO","SUPPORTS_SOFTWARE_VERSION","TIMERS_AND_ALARMS","SUPPORTS_LOCALE_SWITCH","ARTHUR_TARGET","SOUND_SETTINGS","REMINDERS","DIALOG_INTERFACE_VERSION"],"charging":null,"clusterMembers":[],"deviceAccountId":"A159HL3V8OMRNZ","deviceFamily":"FIRE_TV","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"ADVBD696BHNV5","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"70940514603302JH","softwareVersion":"662663720"},{"accountName":"Wohnung","appDeviceList":[],"capabilities":["AMAZON_MUSIC","MICROPHONE","TIDAL","PANDORA","VOLUME_SETTING","AUDIBLE","SALMON","I_HEART_RADIO","APPLE_MUSIC","TUNE_IN","MUSIC_SKILL","AUDIO_PLAYER","KINDLE_BOOKS","SIRIUSXM","DEEZER"],"charging":null,"clusterMembers":["G090U610916420KJ","G09183091056058K","G0911M079406180P"],"deviceAccountId":"A00087432OQ8XJFXWT00","deviceFamily":"WHA","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A3C9PE6TNYLTCH","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"edbb7e932cf347c7b287a5db19c3ee30","softwareVersion":"0"},{"accountName":"Fire  TV  Cube","appDeviceList":[],"capabilities":["ADAPTIVE_LISTENING","EARCONS","AMAZON_MUSIC","ASCENDING_ALARM_VOLUME","PAIR_BT_SINK","SUPPORTS_LOCALE","VOICE_TRAINING","TIMERS_ALARMS_NOTIFICATIONS_VOLUME","PANDORA","CHANGE_NAME","BT_PAIRING_FLOW_V2","ACTIVE_AFTER_FRO","SALMON","SUPPORTS_SOFTWARE_VERSION","TIMERS_AND_ALARMS","SUPPORT_CALENDAR_ALERT","APPLE_MUSIC","SUPPORTS_LOCALE_SWITCH","SOUND_SETTINGS","ARTHUR_TARGET","REMINDERS","SPEECH_RECOGNIZER_USS","SET_LOCALE","TUNE_IN","AUDIO_PLAYER","KINDLE_BOOKS","SLEEP","MICROPHONE","PERSISTENT_CONNECTION","DREAM_TRAINING","TIDAL","SHARKNADO","MULTI_WAKEWORDS_SUPPORTED","GOLDFISH","CUSTOM_ALARM_TONE","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","FLASH_BRIEFING","AUDIBLE","I_HEART_RADIO","FAR_FIELD_WAKE_WORD","DIALOG_INTERFACE_VERSION","MUSIC_SKILL","SIRIUSXM","DEEZER"],"charging":null,"clusterMembers":[],"deviceAccountId":"A07651723SRV0G2RLZ9S","deviceFamily":"FIRE_TV","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A2JKHJ0PX4J3L3","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"G0911X03941304ML","softwareVersion":"21039196292"},{"accountName":"Echo  Dot  Flur","appDeviceList":[],"capabilities":["PAIR_BT_SOURCE","SUPPORTS_LOCALE","ALEXA_VOICE","VOICE_TRAINING","CHANGE_NAME","TUPLE","ACTIVE_AFTER_FRO","TIMERS_AND_ALARMS","SOUND_SETTINGS","REMINDERS","GUARD_EARCON","TUNE_IN","KINDLE_BOOKS","MICROPHONE","DREAM_TRAINING","MULTI_WAKEWORDS_SUPPORTED","VOLUME_SETTING","GOLDFISH","CUSTOM_ALARM_TONE","EQUALIZER_CONTROLLER_TREBLE","AUDIBLE","AUDIO_CONTROLS","DIALOG_INTERFACE_VERSION","MUSIC_SKILL","SIRIUSXM","ADAPTIVE_LISTENING","EARCONS","AMAZON_MUSIC","PAIR_BT_SINK","TUPLE_CATEGORY_A","ASCENDING_ALARM_VOLUME","ALEXA_PRESENCE","EQUALIZER_CONTROLLER_MIDRANGE","TIMERS_ALARMS_NOTIFICATIONS_VOLUME","PANDORA","SET_TIME_ZONE","BT_PAIRING_FLOW_V2","SALMON","SUPPORTS_SOFTWARE_VERSION","GADGETS","SUPPORT_CALENDAR_ALERT","APPLE_MUSIC","SUPPORTS_LOCALE_SWITCH","SPEECH_RECOGNIZER_USS","DEREGISTER_DEVICE","SET_LOCALE","EFDCARDS","AUDIO_PLAYER","SLEEP","PERSISTENT_CONNECTION","TIDAL","PAIR_REMOTE","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","FLASH_BRIEFING","UPDATE_WIFI","I_HEART_RADIO","DS_VOLUME_SETTING","LEMUR_ALPHA","FAR_FIELD_WAKE_WORD","TAHOE_BYOD","REQUIRES_OOBE_FOR_SETUP","EQUALIZER_CONTROLLER_BASS","POPTART","DEEZER"],"charging":null,"clusterMembers":[],"deviceAccountId":"A01378201SS79J7AJ7XMS","deviceFamily":"ECHO","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A1RABVCI4QCIKC","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":["edbb7e932cf347c7b287a5db19c3ee30"],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"G0911M079406180P","softwareVersion":"5805753220"},{"accountName":"Echo  Dot  Küche","appDeviceList":[],"capabilities":["PAIR_BT_SOURCE","SUPPORTS_LOCALE","ALEXA_VOICE","VOICE_TRAINING","CHANGE_NAME","TUPLE","ACTIVE_AFTER_FRO","TIMERS_AND_ALARMS","SOUND_SETTINGS","REMINDERS","GUARD_EARCON","TUNE_IN","KINDLE_BOOKS","MICROPHONE","DREAM_TRAINING","MULTI_WAKEWORDS_SUPPORTED","VOLUME_SETTING","GOLDFISH","CUSTOM_ALARM_TONE","EQUALIZER_CONTROLLER_TREBLE","AUDIBLE","DEREGISTER_FACTORY_RESET","AUDIO_CONTROLS","DIALOG_INTERFACE_VERSION","MUSIC_SKILL","SIRIUSXM","ADAPTIVE_LISTENING","EARCONS","AMAZON_MUSIC","PAIR_BT_SINK","TUPLE_CATEGORY_A","ASCENDING_ALARM_VOLUME","ALEXA_PRESENCE","EQUALIZER_CONTROLLER_MIDRANGE","TIMERS_ALARMS_NOTIFICATIONS_VOLUME","PANDORA","BT_PAIRING_FLOW_V2","SALMON","SUPPORTS_SOFTWARE_VERSION","GADGETS","SUPPORT_CALENDAR_ALERT","APPLE_MUSIC","SUPPORTS_LOCALE_SWITCH","SPEECH_RECOGNIZER_USS","DEREGISTER_DEVICE","SET_LOCALE","EFDCARDS","AUDIO_PLAYER","SLEEP","PERSISTENT_CONNECTION","TIDAL","PAIR_REMOTE","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","FLASH_BRIEFING","UPDATE_WIFI","I_HEART_RADIO","DS_VOLUME_SETTING","LEMUR_ALPHA","FAR_FIELD_WAKE_WORD","TAHOE_BYOD","REQUIRES_OOBE_FOR_SETUP","EQUALIZER_CONTROLLER_BASS","POPTART","DEEZER"],"charging":null,"clusterMembers":[],"deviceAccountId":"A10336463KM6ANCFBSROV","deviceFamily":"ECHO","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A32DOYMUN6DTXA","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":["edbb7e932cf347c7b287a5db19c3ee30"],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"G090U610916420KJ","softwareVersion":"5805753476"},{"accountName":"Echo  Show  Schlafzimmer","appDeviceList":[],"capabilities":["TUPLE_CATEGORY_B","SUPPORTS_LOCALE","ALEXA_VOICE","VOICE_TRAINING","CHANGE_NAME","TUPLE","TIMERS_AND_ALARMS","SOUND_SETTINGS","REMINDERS","GUARD_EARCON","TUNE_IN","KINDLE_BOOKS","MICROPHONE","DREAM_TRAINING","SHARKNADO","MULTI_WAKEWORDS_SUPPORTED","VOLUME_SETTING","GOLDFISH","CUSTOM_ALARM_TONE","EQUALIZER_CONTROLLER_TREBLE","AUDIBLE","AUDIO_CONTROLS","DIALOG_INTERFACE_VERSION","MUSIC_SKILL","SIRIUSXM","ADAPTIVE_LISTENING","EARCONS","AMAZON_MUSIC","ASCENDING_ALARM_VOLUME","PAIR_BT_SINK","ALEXA_PRESENCE","EQUALIZER_CONTROLLER_MIDRANGE","PANDORA","TIMERS_ALARMS_NOTIFICATIONS_VOLUME","BT_PAIRING_FLOW_V2","SALMON","SUPPORTS_SOFTWARE_VERSION","SUPPORT_CALENDAR_ALERT","APPLE_MUSIC","SUPPORTS_LOCALE_SWITCH","SPEECH_RECOGNIZER_USS","SET_LOCALE","EFDCARDS","FACTORY_RESET_DEVICE","AUDIO_PLAYER","SLEEP","PERSISTENT_CONNECTION","TIDAL","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","FLASH_BRIEFING","I_HEART_RADIO","DS_VOLUME_SETTING","LEMUR_ALPHA","FAR_FIELD_WAKE_WORD","EQUALIZER_CONTROLLER_BASS","POPTART","DEEZER","LIVE_VIEW"],"charging":null,"clusterMembers":[],"deviceAccountId":"A063800733RIXTXAV2E0V","deviceFamily":"KNIGHT","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A1Z88NGR2BK6A2","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":["edbb7e932cf347c7b287a5db19c3ee30"],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"G09183091056058K","softwareVersion":"5805754756"},{"accountName":"This   Device","appDeviceList":[{"deviceAccountId":"A0677275IETJ8P5WNXLX","deviceType":"A2IVLV5VM2W81","serialNumber":"87ba03d8a92b898ff3e2a5c99dfec165"},{"deviceAccountId":"A0305194VW9O0KVSCYQ1","deviceType":"A2TF17PFR55MTB","serialNumber":"0e04d8c1b73441e4a99110c749a5c5b4"},{"deviceAccountId":"A026176610BR5KGLF1W15","deviceType":"A2IVLV5VM2W81","serialNumber":"c0762bc600e4285baf43afb81d34ac9f"},{"deviceAccountId":"A07533506XAPMCE5GKBX","deviceType":"A2IVLV5VM2W81","serialNumber":"21c59241ed82e98a939e5f47592a8d7e"}],"capabilities":["ADAPTIVE_LISTENING","MICROPHONE","VOLUME_SETTING"],"charging":null,"clusterMembers":[],"deviceAccountId":"A07533506XAPMCE5GKBX","deviceFamily":"VOX","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A2IVLV5VM2W81","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"21c59241ed82e98a939e5f47592a8d7e","softwareVersion":"1"},{"accountName":"Stephan's  Alexa  Apps","appDeviceList":[{"deviceAccountId":"A06175881I2SREN19MYMG","deviceType":"A1DL2DVDQVK3Q","serialNumber":"SMG985F5B8874995CD23CCC"}],"capabilities":["ADAPTIVE_LISTENING","MICROPHONE","VOLUME_SETTING"],"charging":null,"clusterMembers":[],"deviceAccountId":"A06175881I2SREN19MYMG","deviceFamily":"AMAZONMOBILEMUSIC_ANDROID","deviceOwnerCustomerId":"AV8T15OWSJBT1","deviceType":"A1DL2DVDQVK3Q","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":false,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"SMG985F5B8874995CD23CCC","softwareVersion":"516140110"}]}
alexa2.0 | 2021-10-11 12:18:07.102 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/devices-v2/device?cached=true&_=1633947487102","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:07.101 | debug | Alexa-Remote: No authentication check needed (time elapsed 603)
alexa2.0 | 2021-10-11 12:18:07.100 | debug | Alexa-Remote:  Response:  [{"commsId":"amzn1.comms.id.person.amzn1~amzn1.account.AE2K6HEV5O4UZ6LEM2FHPTHLEDXA","directedId":"amzn1.account.AE2K6HEV5O4UZ6LEM2FHPTHLEDXA","phoneCountryCode":"49","phoneNumber":"1729887930","firstName":"Stephan","lastName":"Kreyenborg","phoneticFirstName":null,"phoneticLastName":null,"commsProvisionStatus":"PROVISIONED","isChild":false,"personIdV2":"amzn1.actor.person.oid.A2P02UVLYMB4FY","signedInUser":true,"commsProvisioned":true,"enrolledInAlexa":true,"speakerProvisioned":false}]
alexa2.0 | 2021-10-11 12:18:06.500 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa-comms-mobile-service.amazon.de","path":"/accounts","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:06.499 | debug | Alexa-Remote: No authentication check needed (time elapsed 1)
alexa2.0 | 2021-10-11 12:18:06.497 | debug | Alexa-Remote: Authentication checked: true
alexa2.0 | 2021-10-11 12:18:06.495 | debug | Alexa-Remote:  Response:  {"authentication":{"authenticated":true,"canAccessPrimeMusicContent":true,"customerEmail":"info@skb-web.de","customerId":"AV8T15OWSJBT1","customerName":"Stephan  Kreyenborg"}}
alexa2.0 | 2021-10-11 12:18:05.911 | debug | Alexa-Remote:  Sending Request with  {"host":"alexa.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-10-11 12:18:05.909 | debug | Alexa-Remote: cookie was provided
alexa2.0 | 2021-10-11 12:18:05.904 | debug | Alexa-Remote: Use as Base-URL: alexa.amazon.de
alexa2.0 | 2021-10-11 12:18:05.903 | debug | Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2021-10-11 12:18:05.902 | debug | Alexa-Remote:  Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36  (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
alexa2.0 | 2021-10-11 12:18:05.125 | info | starting. Version 3.10.4 in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.18.0, js-controller: 3.3.18
alexa2.0 | 2021-10-11 12:18:04.842 | debug | Plugin sentry Initialize Plugin (enabled=true)
alexa2.0 | 2021-10-11 12:18:04.663 | debug | statesDB connected
alexa2.0 | 2021-10-11 12:18:04.661 | debug | States connected to redis: 127.0.0.1:6379
alexa2.0 | 2021-10-11 12:18:04.651 | debug | States create User PubSub Client
alexa2.0 | 2021-10-11 12:18:04.649 | debug | States create System PubSub Client
alexa2.0 | 2021-10-11 12:18:04.639 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
alexa2.0 | 2021-10-11 12:18:04.636 | debug | objectDB connected
alexa2.0 | 2021-10-11 12:18:04.624 | debug | Objects connected to redis: 127.0.0.1:6379
alexa2.0 | 2021-10-11 12:18:04.597 | debug | Objects client initialize lua scripts
alexa2.0 | 2021-10-11 12:18:04.595 | debug | Objects create User PubSub Client
alexa2.0 | 2021-10-11 12:18:04.593 | debug | Objects create System PubSub Client
alexa2.0 | 2021-10-11 12:18:04.589 | debug | Objects client ready ... initialize now
alexa2.0 | 2021-10-11 12:18:04.507 | debug | Redis Objects: Use Redis connection: 127.0.0.1:6379
host.ioBroker | 2021-10-11 12:18:03.076 | info | instance system.adapter.alexa2.0 started with pid 5972


</body>
</html>

**Comment by Apollon77** [comment]
System uptodate and all?
