### ISSUE TITLE
Support voice profiles in History

### ISSUE THREAD

**Issue by Kaldesh84** [Apollon77/ioBroker.alexa2#910]
In the Alexa app there is an extra tab next to the activity that tracks audio recordings and also links them to a known voice profile if possible.
Could that information (if available) be added to the entries in alexa2.X.History?

I would like to have Alexa routines trigger actions in ioBroker. With the information of the used Voice Profile I would be able to react to the routine call in a personalized manner.

For example my wife and I both have a car with some data in ioBroker we could just have a routine that asks for the status of the "car" and by the information of the voice profile the logic could determine which data points to read from. Or we could open the correct garage door depending on the voice profile.

I've considered using my ESPresense system to decide who COULD have talked to what Echo device but that all doesn't work anymore as soon as we're both in the same room.

![2022-07-04 11_59_49-https___www amazon de_alexa-privacy_apd_rvh](https://user-images.githubusercontent.com/79861507/177132193-db0592f7-36ee-48a6-822a-9e93290f1e5d.png)

**Comment by Apollon77** [comment]
this was already discussed in the forum ... The issue is that the person Info is available roughly 10s after the action was done ... Because of the fact that the adapter queries the data very fast and also the users want to get the history entries very fast there is no way to get these infos. Only possibility would be to somehow query the same interactions again 10+s later and put another record to "add" these infos, but what would that help anyone? Thanyk why this is not making sense right now, sorry
