### ISSUE TITLE
ultrasonic motion detection for EchoDOT gen.5

### ISSUE THREAD

**Issue by vonCartman** [Apollon77/ioBroker.alexa2#992]
is it possible to integrate the new function of EchoDot gen.5:

ultrasonic motion detection for EchoDOT gen.5?

**Comment by Apollon77** [comment]
No, because such values are not actively reported on change and so there is not way to get " the short timepoint when it triggers". The workaround is the following:
* create an own state in iobroker as button
* use iot adapter to expose this as button to Alexa
* create a routine that reacts on trigger of the detection and that "turns on" that device/state 
With this you should get a trigger when it is activated and you can react with a script in iobroker on it
