### ISSUE TITLE
Can I start a dialogue with this adapter?

### ISSUE THREAD

**Issue by jtolksdo** [Apollon77/ioBroker.alexa2#999]
Hi,
I'm not quite sure if this is possible at all with Alexa so far, hence I'm asking.
I'd like to start a triggered dialogue with the adapter, in order to do some activities.
My use case is to shut down all lights at midnight, but before shutting down all lights I'd like to ask through Alexa, if someone is present and needs the light.

So, sending a question like "Hey, I'd like to shut down the lights in the living room now. Do you agree?".
If there's no user input, the routing will progress shutting down the light.
In case the user in the living room say no, nothing happens. 
 
Would that work, or do I need to write a skill on my own?

**Comment by Apollon77** [comment]
Alexa normall yonly listenes when it is actively asked for something. So "speaking a sentence and listen then" is not possible - also not with a Skill!! Because any skill needs to be triggered.

We currently testing a new Custom Skill (german only right now) which in combination with alexa2 Adapter could achieve something like this ... see https://forum.iobroker.net/post/906279 for more details

**Comment by jtolksdo** [comment]
@Apollon77 really cool, will check
